### ISSUE TITLE
How to download/fork the Overleaf project?

### ISSUE THREAD

**Issue by SuperBruceJia** [guanyingc/cv_rebuttal_template#1]
Dear Guanying,

Thank you for your warm share! It helps a lot.

Could you please share the download Overleaf links of the two projects so that I could fork the projects?

[1] CVPR Paper Submission Overleaf Project
[2] CVPR Rebuttal Overleaf Project

Thank you very much!

Shuyue
Oct. 28th, 2022

**Comment by guanyingc** [comment]
Hi,

You can click the menu at the top left, and then download the source or copy.
![overleaf_menu](https://user-images.githubusercontent.com/8651158/198560755-b906f6fd-4a18-405c-8c86-aa7e9b7e195c.png)

![download_copy](https://user-images.githubusercontent.com/8651158/198560669-7cf110d7-45ed-43fb-9b1c-df3cb94c92ed.png)

**Comment by SuperBruceJia** [comment]
Dear Guanying,

Well received with thanks!

Best regards,

Shuyue
Oct. 28th, 2022
